### ISSUE TITLE
SysCallError: (-1, 'Unexpected EOF')

### ISSUE THREAD

**Issue by awidgery** [stephenmuss/django-ios-notifications#25]
A blip in the normally flawless django-ios-notifications:

If it makes any difference I am running this within a function called with an `@async` decorator from [here](https://django-utils.readthedocs.org/en/latest/django-utils/decorators.html).

```
Exception in thread Thread-92:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/ubuntu/Live/snaplist-website/main/apn.py", line 54, in run
    sendAPNMessage(self.device_id, self.message, self.data, self.badge)
  File "/home/ubuntu/Live/snaplist-website/main/apn.py", line 42, in sendAPNMessage
    apns.push_notification_to_devices(notification, devices)
  File "/usr/local/lib/python2.7/dist-packages/ios_notifications/models.py", line 99, in push_notification_to_devices
    self._write_message(notification, devices, chunk_size)
  File "/usr/local/lib/python2.7/dist-packages/ios_notifications/models.py", line 121, in _write_message
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/ios_notifications/models.py", line 89, in _connect
    return super(APNService, self)._connect(self.certificate, self.private_key, self.passphrase)
  File "/usr/local/lib/python2.7/dist-packages/ios_notifications/models.py", line 55, in _connect
    self.connection.do_handshake()
SysCallError: (-1, 'Unexpected EOF')
```

**Comment by bradens** [comment]
I'm getting this, anyone figure out what was going on?
