### ISSUE TITLE
Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')]

### ISSUE THREAD

**Issue by kokhoor** [stephenmuss/django-ios-notifications#82]
Hi,

    I am using django-ios-notification 0.2.0, pyOpenSSL 16.2.0

The connection to Apple Production APNS: gateway.push.apple.com is via TLSv1:

`context = OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_METHOD)`

But I received "tlsv1 alert internal error" when trying to send notification. Has anyone experience this issue before. and what is the resolution?

Thanks in advance. The log is below:
 
```
>>> apns.push_notification_to_devices(notification, (devices[0],))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\apps\vMoonlight2\lib\site-packages\ios_notifications\models.py", line
 110, in push_notification_to_devices
    self._write_message(notification, devices, chunk_size)
  File "c:\apps\vMoonlight2\lib\site-packages\ios_notifications\models.py", line
 132, in _write_message
    self._connect()
  File "c:\apps\vMoonlight2\lib\site-packages\ios_notifications\models.py", line
 100, in _connect
    return super(APNService, self)._connect(self.certificate, self.private_key,
self.passphrase)
  File "c:\apps\vMoonlight2\lib\site-packages\ios_notifications\models.py", line
 64, in _connect
    self.connection.do_handshake()
  File "c:\apps\vMoonlight2\lib\site-packages\OpenSSL\SSL.py", line 1426, in do_
handshake
    self._raise_ssl_error(self._ssl, result)
  File "c:\apps\vMoonlight2\lib\site-packages\OpenSSL\SSL.py", line 1174, in _ra
ise_ssl_error
    _raise_current_error()
  File "c:\apps\vMoonlight2\lib\site-packages\OpenSSL\_util.py", line 48, in exc
eption_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')]
```

**Comment by kokhoor** [comment]
Python version is 2.7.11

**Comment by kokhoor** [comment]
Sorry, is resolved. This is due to an expired cert. Creating the apple APNS new cert solves the problem.
